---
apiVersion: v1
kind: Service
metadata:
  name: springboot-hello-nodeport
spec:
  type: NodePort
  selector:
    app: springboot-hello
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30001