name: Build and upload artifact Pipeline

on: 
  push:
    branches:
      - feature/springbootbuild

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v4

      - name: Set Up Java
        id: setup-java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Artifact
        id: build
        run: |
          mvn clean package --file pom.xml
          mkdir -p artifact && cp target/*.jar artifact/

      - name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: artifact/
