name: Build Pipeline

on: 
  push:
    branches:
      - feature/docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v4

      - name: Set Up Java
        id: setup-java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven Dependencies
        id: cache-maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Build Artifact
        id: build
        run: |
          mvn clean package --file pom.xml
          mkdir -p artifact && cp target/*.jar artifact/

      - name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: artifact/

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v4

      - name: Download Maven Artifact
        id: downloadArtifact
        uses: actions/download-artifact@v4
        with:
          name: package
          path: artifact/

      - name: Build Docker Image
        id: buildDockerImage
        run: |
          docker build -t springboothello:v1 .
      
      - name: List Docker Images
        id: listDockerImages
        run: docker images